### ISSUE TITLE
(feature request) Add notification toggle

### ISSUE THREAD

**Issue by xaviergmail** [XertroV/tm-plugin-hotkeys#2]
This plugin is great! I have it bound to disable all overlay plugins to be able to quickly focus on driving when necessary. The plugins I control with hotkeys play nice with being enabled/disabled quickly with no apparent performance impacts.

However, the enable/disable notifications tend to pile up when I press the hotkey too quickly:
![image](https://github.com/XertroV/tm-plugin-hotkeys/assets/522034/b5462fbd-0c04-4d49-8a5e-6f88f886d050)

Therefore, having an option to disable these notifications would be fantastic. Thanks for your consideration!

**Comment by XertroV** [comment]
can do

**Comment by XertroV** [comment]
@xaviergmail submitted an update, should be live soon
